version: '2'
services:
  virtuoso:
    build: ./virtuoso
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "https://w3id.org/arco"
    volumes:
      - ./virtuoso/graphs:/graphs
    ports:
      - "8890:8890"
    restart: always
  lode:
    build: ./lode
    ports:
      - "9090:8080"
    restart: always
  httpd:
    build: ./httpd
    ports:
      - "8080:80"
    restart: always